databases:
  - name: airbyte-db
    plan: starter
    databaseName: airbyte
    user: airbyte

services:
  - type: pserv
    env: docker
    name: init
    dockerfilePath: ./dockerfiles/init/Dockerfile

  # seed:
  #   image: airbyte/seed:${VERSION}
  #   container_name: airbyte-data-seed
  #   # Pre-populate the volume if it is empty.
  #   # See: https://docs.docker.com/storage/volumes/#populate-a-volume-using-a-container
  #   volumes:
  #     - data:/app/seed
  # scheduler:
  #   image: airbyte/scheduler:${VERSION}
  #   container_name: airbyte-scheduler
  #   environment:
  #     - DATABASE_USER=${DATABASE_USER}
  #     - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  #     - DATABASE_URL=jdbc:postgresql://db:5432/${DATABASE_DB}
  #     - WAIT_BEFORE_HOSTS=5
  #     - WAIT_HOSTS_TIMEOUT=45
  #     - WAIT_HOSTS=db:5432
  #     - WORKSPACE_ROOT=${WORKSPACE_ROOT}
  #     - WORKSPACE_DOCKER_MOUNT=${WORKSPACE_DOCKER_MOUNT}
  #     - LOCAL_DOCKER_MOUNT=${LOCAL_DOCKER_MOUNT}
  #     - CONFIG_ROOT=${CONFIG_ROOT}
  #     - TRACKING_STRATEGY=${TRACKING_STRATEGY}
  #     - AIRBYTE_VERSION=${VERSION}
  #     - AIRBYTE_ROLE=${AIRBYTE_ROLE:-}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - workspace:${WORKSPACE_ROOT}
  #     - ${LOCAL_ROOT}:${LOCAL_ROOT}
  #     - data:${CONFIG_ROOT}
  # server:
  #   image: airbyte/server:${VERSION}
  #   container_name: airbyte-server
  #   environment:
  #     - DATABASE_USER=${DATABASE_USER}
  #     - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  #     - DATABASE_URL=jdbc:postgresql://db:5432/${DATABASE_DB}
  #     - WAIT_BEFORE_HOSTS=5
  #     - WAIT_HOSTS_TIMEOUT=45
  #     - WAIT_HOSTS=db:5432
  #     - CONFIG_ROOT=${CONFIG_ROOT}
  #     - TRACKING_STRATEGY=${TRACKING_STRATEGY}
  #     - AIRBYTE_VERSION=${VERSION}
  #     - AIRBYTE_ROLE=${AIRBYTE_ROLE:-}
  #     - WORKSPACE_ROOT=${WORKSPACE_ROOT}
  #   ports:
  #     - 8001:8001
  #   volumes:
  #     - workspace:${WORKSPACE_ROOT}
  #     - data:${CONFIG_ROOT}
  # webapp:
  #   image: airbyte/webapp:${VERSION}
  #   container_name: airbyte-webapp
  #   ports:
  #     - 8000:80
  #   environment:
  #     - AIRBYTE_ROLE=${AIRBYTE_ROLE:-}
  #     - AIRBYTE_VERSION=${VERSION}
  #     - API_URL=${API_URL}
  #     - IS_DEMO=${IS_DEMO:-}
  #     - PAPERCUPS_STORYTIME=${PAPERCUPS_STORYTIME:-}
  #     - TRACKING_STRATEGY=${TRACKING_STRATEGY}
  # airbyte-temporal:
  #   image: temporalio/auto-setup:1.7.0
  #   container_name: airbyte-temporal
  #   ports:
  #     - 7233:7233
  #   environment:
  #     - DB=postgresql
  #     - DB_PORT=5432
  #     - POSTGRES_USER=${DATABASE_USER}
  #     - POSTGRES_PWD=${DATABASE_PASSWORD}
  #     - POSTGRES_SEEDS=db
  #     - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
  #   volumes:
  #     - ./temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
